title: Architecture & Performance
description: > # this means to ignore newlines until "twitter_username:"
  databases, dataviz, datascience
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: architecture-performance
github_username:  aetperf
twitter_username: 
author:
  name: A&P
  email: contact@architecture-performance.fr


google_analytics: G-B2W567YB76

show_excerpts: false

# Build settings
# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# markdown
markdown: kramdown
