theme: jekyll-theme-minimal
title: Architecture & Performance
description: Databases, Dataviz, Machine Learning

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "./img/aetp.png"
